import type { Board, BoardEdge, BoardNode, Card, Project } from "@chitra/core";

/** Walk a TipTap-shaped doc and stitch all text leaves together. */
export function flattenBody(card: Card): string {
  const out: string[] = [];
  const visit = (n: unknown): void => {
    if (!n || typeof n !== "object") return;
    const node = n as { type?: string; text?: string; content?: unknown[] };
    if (node.type === "text" && typeof node.text === "string") out.push(node.text);
    if (Array.isArray(node.content)) node.content.forEach(visit);
  };
  visit(card.body);
  return out.join("").trim();
}

/**
 * Topological sort of nodes by edges. Cycle-safe — any nodes still pending
 * after Kahn's algorithm finishes are appended at the end in their original
 * order so nothing is lost.
 */
export function topoOrder(nodes: BoardNode[], edges: BoardEdge[]): BoardNode[] {
  const indeg = new Map<string, number>(nodes.map((n) => [n.id, 0]));
  const adj = new Map<string, string[]>(nodes.map((n) => [n.id, []]));
  for (const e of edges) {
    if (!indeg.has(e.source) || !indeg.has(e.target)) continue;
    adj.get(e.source)!.push(e.target);
    indeg.set(e.target, (indeg.get(e.target) ?? 0) + 1);
  }
  const queue = nodes.filter((n) => (indeg.get(n.id) ?? 0) === 0).map((n) => n.id);
  const visited = new Set<string>();
  const order: string[] = [];
  while (queue.length > 0) {
    const id = queue.shift()!;
    if (visited.has(id)) continue;
    visited.add(id);
    order.push(id);
    for (const next of adj.get(id) ?? []) {
      indeg.set(next, (indeg.get(next) ?? 0) - 1);
      if ((indeg.get(next) ?? 0) <= 0) queue.push(next);
    }
  }
  // Append cycle survivors so we never silently drop content.
  for (const n of nodes) if (!visited.has(n.id)) order.push(n.id);
  const byId = new Map(nodes.map((n) => [n.id, n]));
  return order.map((id) => byId.get(id)!).filter(Boolean);
}

/* ------------------------------------------------------------------ *
 *  Markdown                                                           *
 * ------------------------------------------------------------------ */

export function projectToMarkdown(project: Project): string {
  const lines: string[] = [];
  lines.push(`# ${project.name}`, "");
  lines.push(`> Generated by Chitra — ${new Date().toISOString()}`, "");

  for (const board of project.boards) {
    lines.push(`## Board — ${board.name}`, "");
    if (board.nodes.length === 0) {
      lines.push("_Empty board._", "");
      continue;
    }
    const cardById = new Map(project.cards.map((c) => [c.id, c]));
    const ordered = topoOrder(board.nodes, board.edges);
    const outgoing = new Map<string, BoardEdge[]>();
    for (const e of board.edges) {
      if (!outgoing.has(e.source)) outgoing.set(e.source, []);
      outgoing.get(e.source)!.push(e);
    }

    for (const node of ordered) {
      const card = cardById.get(node.cardId);
      if (!card) continue;
      lines.push(`### ${card.title}`, "");
      lines.push(`*Type:* \`${card.type}\``);
      if (card.tags.length > 0) lines.push(`*Tags:* ${card.tags.map((t) => `\`${t}\``).join(", ")}`);
      lines.push("");
      const body = flattenBody(card);
      if (body) lines.push(body, "");

      const outs = outgoing.get(node.id) ?? [];
      if (outs.length > 0) {
        lines.push("**Connections:**");
        for (const e of outs) {
          const targetNode = board.nodes.find((n) => n.id === e.target);
          const targetCard = targetNode ? cardById.get(targetNode.cardId) : undefined;
          if (!targetCard) continue;
          lines.push(`- _${e.kind}_ → ${targetCard.title}${e.label ? ` (${e.label})` : ""}`);
        }
        lines.push("");
      }
    }
  }

  // Orphan cards (not on any board) get their own section.
  const onBoard = new Set<string>();
  for (const b of project.boards) for (const n of b.nodes) onBoard.add(n.cardId);
  const orphans = project.cards.filter((c) => !onBoard.has(c.id));
  if (orphans.length > 0) {
    lines.push("## Inbox (unplaced cards)", "");
    for (const c of orphans) {
      lines.push(`- **${c.title}** (\`${c.type}\`) — ${flattenBody(c) || "_no body_"}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/* ------------------------------------------------------------------ *
 *  Mermaid (flowchart) — diagram-only export                          *
 * ------------------------------------------------------------------ */

/** Map domain edge kinds to Mermaid arrow syntax. */
function mermaidArrow(kind: BoardEdge["kind"]): string {
  switch (kind) {
    case "depends-on":
    case "conflicts-with":
      return "-.->";
    case "informs":
      return "-..->";
    case "contains":
      return "===>";
    case "sequence":
    case "flows-to":
    case "straight":
    default:
      return "-->";
  }
}

/** Sanitize a string for use as a Mermaid node id (alphanum + underscore). */
function mermaidId(raw: string): string {
  const cleaned = raw.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[A-Za-z]/.test(cleaned) ? cleaned : `n_${cleaned}`;
}

/** Escape a label for Mermaid (quoted form supports most chars). */
function mermaidLabel(raw: string): string {
  return raw.replace(/"/g, "&quot;").replace(/\n/g, " ");
}

/**
 * Render a project board as a Mermaid `flowchart TD` block. If `boardId` is
 * omitted, the first board is used. Returns a string ready to drop into a
 * `.mmd` file or a fenced `mermaid` code block.
 */
export function projectToMermaid(project: Project, boardId?: string): string {
  const board =
    (boardId ? project.boards.find((b) => b.id === boardId) : undefined) ??
    project.boards[0];
  if (!board) return "flowchart TD\n  empty[\"(no board)\"]\n";

  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const lines: string[] = [];
  lines.push(`%% ${project.name} — ${board.name}`);
  lines.push(`%% Generated by Chitra on ${new Date().toISOString()}`);
  lines.push("flowchart TD");

  if (board.nodes.length === 0) {
    lines.push("  empty[\"(empty board)\"]");
    return lines.join("\n") + "\n";
  }

  for (const node of board.nodes) {
    const card = cardById.get(node.cardId);
    const title = card?.title ?? "(missing card)";
    lines.push(`  ${mermaidId(node.id)}["${mermaidLabel(title)}"]`);
  }

  for (const edge of board.edges) {
    const arrow = mermaidArrow(edge.kind);
    const labelPart = edge.label
      ? `|${mermaidLabel(edge.label)}|`
      : edge.kind === "straight"
        ? ""
        : `|${edge.kind}|`;
    lines.push(`  ${mermaidId(edge.source)} ${arrow}${labelPart} ${mermaidId(edge.target)}`);
  }

  return lines.join("\n") + "\n";
}

/* ------------------------------------------------------------------ *
 *  Print-friendly HTML (used by main.printToPDF)                      *
 * ------------------------------------------------------------------ */

export type PrintHtmlOptions = {
  /** Optional PNG data URL of the canvas snapshot to embed at the top. */
  canvasImageDataUrl?: string;
  /** Restrict to a single board id (default: all boards). */
  boardId?: string;
};

export function projectToPrintHtml(project: Project, opts: PrintHtmlOptions = {}): string {
  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const boards = opts.boardId
    ? project.boards.filter((b) => b.id === opts.boardId)
    : project.boards;

  const escape = (s: string): string =>
    s.replace(/[&<>"']/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[m]!));

  const renderCard = (c: Card): string => {
    const body = flattenBody(c);
    const tags =
      c.tags.length > 0
        ? `<div class="tags">${c.tags.map((t) => `<span>#${escape(t)}</span>`).join(" ")}</div>`
        : "";
    return `
      <article class="card card--${escape(c.type)}">
        <header>
          <span class="type">${escape(c.type)}</span>
          <h3>${escape(c.title)}</h3>
        </header>
        ${body ? `<p>${escape(body)}</p>` : ""}
        ${tags}
      </article>`;
  };

  const renderBoard = (b: Board): string => {
    const ordered = topoOrder(b.nodes, b.edges);
    const cards = ordered
      .map((n) => cardById.get(n.cardId))
      .filter((c): c is Card => Boolean(c))
      .map(renderCard)
      .join("\n");
    const edgeRows =
      b.edges.length === 0
        ? ""
        : `<table class="edges"><thead><tr><th>From</th><th>Kind</th><th>To</th><th>Label</th></tr></thead><tbody>${b.edges
            .map((e) => {
              const s = b.nodes.find((n) => n.id === e.source);
              const t = b.nodes.find((n) => n.id === e.target);
              const sc = s ? cardById.get(s.cardId) : undefined;
              const tc = t ? cardById.get(t.cardId) : undefined;
              return `<tr><td>${escape(sc?.title ?? "")}</td><td><code>${escape(e.kind)}</code></td><td>${escape(tc?.title ?? "")}</td><td>${escape(e.label ?? "")}</td></tr>`;
            })
            .join("")}</tbody></table>`;
    return `
      <section class="board">
        <h2>${escape(b.name)}</h2>
        ${cards}
        ${edgeRows}
      </section>`;
  };

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${escape(project.name)}</title>
<style>
  @page { size: A4; margin: 18mm 14mm; }
  :root {
    --ink: #15151c; --dim: #5a5a6a; --line: #e3e3ea;
    --accent: #7c5cff; --accent2: #21d4fd;
  }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: #fff; color: var(--ink);
    font: 11pt/1.55 "Inter", system-ui, -apple-system, Segoe UI, sans-serif; }
  h1 { font-family: "Fraunces", Georgia, serif; font-size: 28pt; margin: 0 0 4pt; letter-spacing: -0.01em; }
  h2 { font-family: "Fraunces", Georgia, serif; font-size: 18pt; margin: 24pt 0 8pt; padding-bottom: 4pt; border-bottom: 1.5pt solid var(--line); page-break-after: avoid; }
  h3 { font-size: 12pt; margin: 0 0 4pt; }
  .meta { color: var(--dim); font-size: 9pt; margin-bottom: 16pt; }
  .accent-bar { height: 4pt; background: linear-gradient(90deg, var(--accent), var(--accent2)); border-radius: 2pt; margin-bottom: 12pt; }
  .snapshot { width: 100%; border: 0.5pt solid var(--line); border-radius: 6pt; margin-bottom: 12pt; page-break-inside: avoid; }
  .card { border: 0.5pt solid var(--line); border-left: 3pt solid var(--accent); border-radius: 6pt; padding: 8pt 10pt; margin: 6pt 0; page-break-inside: avoid; }
  .card header { display: flex; align-items: baseline; gap: 8pt; margin-bottom: 2pt; }
  .card .type { font-size: 8pt; text-transform: uppercase; letter-spacing: 0.12em; color: var(--dim); }
  .card p { margin: 4pt 0 0; }
  .card .tags { margin-top: 4pt; font-size: 8.5pt; color: var(--dim); }
  .card--goal { border-left-color: #ffb86b; }
  .card--risk { border-left-color: #ff6b6b; }
  .card--metric { border-left-color: #21d4fd; }
  .card--persona { border-left-color: #ff7ad9; }
  .card--component { border-left-color: #7c5cff; }
  .card--step { border-left-color: #6bffb1; }
  .card--decision { border-left-color: #ffd86b; }
  .card--data { border-left-color: #6bd0ff; }
  .card--note { border-left-color: #c0c0cc; }
  .edges { width: 100%; border-collapse: collapse; margin-top: 8pt; font-size: 9.5pt; page-break-inside: avoid; }
  .edges th, .edges td { padding: 4pt 6pt; border-bottom: 0.5pt solid var(--line); text-align: left; }
  .edges th { font-size: 8.5pt; text-transform: uppercase; letter-spacing: 0.1em; color: var(--dim); font-weight: 600; }
</style></head><body>
  <header>
    <h1>${escape(project.name)}</h1>
    <div class="meta">Generated by Chitra on ${new Date().toLocaleString()} · ${project.cards.length} cards · ${project.boards.length} board${project.boards.length === 1 ? "" : "s"}</div>
    <div class="accent-bar"></div>
    ${opts.canvasImageDataUrl ? `<img class="snapshot" src="${opts.canvasImageDataUrl}" alt="Canvas snapshot">` : ""}
  </header>
  ${boards.map(renderBoard).join("\n")}
</body></html>`;
}

/* ------------------------------------------------------------------ *
 *  Interactive HTML (single-file shareable viewer)                    *
 * ------------------------------------------------------------------ */

export function projectToInteractiveHtml(project: Project): string {
  // Compute viewport bbox per board so we can fit the SVG without React Flow.
  const boardsForViewer = project.boards.map((b) => {
    const xs = b.nodes.map((n) => n.position.x);
    const ys = b.nodes.map((n) => n.position.y);
    const ws = b.nodes.map((n) => n.width ?? 280);
    const hs = b.nodes.map((n) => n.height ?? 180);
    const minX = Math.min(0, ...xs);
    const minY = Math.min(0, ...ys);
    const maxX = Math.max(0, ...xs.map((x, i) => x + (ws[i] ?? 280)));
    const maxY = Math.max(0, ...ys.map((y, i) => y + (hs[i] ?? 180)));
    return {
      id: b.id,
      name: b.name,
      bbox: { minX, minY, maxX, maxY },
      nodes: b.nodes,
      edges: b.edges,
    };
  });

  const data = {
    project: {
      id: project.id,
      name: project.name,
      cards: project.cards.map((c) => ({
        id: c.id,
        type: c.type,
        title: c.title,
        body: flattenBody(c),
        tags: c.tags,
      })),
      boards: boardsForViewer,
    },
    generatedAt: new Date().toISOString(),
    appVersion: "chitra-viewer/1",
  };

  const json = JSON.stringify(data).replace(/</g, "\\u003c");

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>${data.project.name} · Chitra viewer</title>
<style>
  :root { --bg: #0b0b10; --panel: #12121a; --ink: #e7e7ee; --dim: #9c9caa; --line: rgba(255,255,255,0.08); --accent: #7c5cff; --accent2: #21d4fd; }
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: var(--bg); color: var(--ink);
    font: 14px/1.5 Inter, system-ui, -apple-system, Segoe UI, sans-serif; height: 100%; }
  body { display: flex; flex-direction: column; }
  header { display: flex; align-items: center; gap: 12px; padding: 10px 16px; border-bottom: 1px solid var(--line); background: #0a0a10; }
  header .logo { width: 12px; height: 12px; border-radius: 50%; background: linear-gradient(135deg, var(--accent), var(--accent2)); }
  header h1 { margin: 0; font-size: 14px; font-weight: 600; }
  header .meta { margin-left: auto; color: var(--dim); font-size: 12px; }
  nav { display: flex; gap: 4px; padding: 8px 12px; border-bottom: 1px solid var(--line); overflow-x: auto; }
  nav button { background: transparent; border: 1px solid transparent; color: var(--dim); padding: 6px 12px; border-radius: 6px; font: inherit; cursor: pointer; white-space: nowrap; }
  nav button.active { background: rgba(255,255,255,0.05); color: var(--ink); border-color: var(--line); }
  nav button:hover { color: var(--ink); }
  main { flex: 1; display: grid; grid-template-columns: 1fr 320px; min-height: 0; }
  .canvas-wrap { position: relative; overflow: auto; background:
    radial-gradient(circle at 20% 30%, rgba(124,92,255,0.10), transparent 40%),
    radial-gradient(circle at 80% 70%, rgba(33,212,253,0.08), transparent 40%),
    var(--bg);
    background-image: radial-gradient(circle, rgba(255,255,255,0.06) 1px, transparent 1px);
    background-size: 24px 24px;
  }
  svg { display: block; }
  .node { fill: #14141d; stroke: rgba(255,255,255,0.12); stroke-width: 1; rx: 12; }
  .node-title { fill: var(--ink); font-size: 13px; font-weight: 600; }
  .node-type { fill: var(--dim); font-size: 10px; text-transform: uppercase; letter-spacing: 0.1em; }
  .node-body { fill: var(--dim); font-size: 11px; }
  .edge { stroke: rgba(255,255,255,0.18); stroke-width: 1.4; fill: none; marker-end: url(#arrow); }
  .edge-label { fill: var(--dim); font-size: 10px; }
  aside { border-left: 1px solid var(--line); background: var(--panel); overflow-y: auto; padding: 16px; }
  aside h2 { font-size: 11px; text-transform: uppercase; letter-spacing: 0.18em; color: var(--dim); margin: 0 0 12px; font-weight: 600; }
  .inbox-card { padding: 10px 12px; border: 1px solid var(--line); border-left: 3px solid var(--accent); border-radius: 8px; margin-bottom: 8px; }
  .inbox-card .t { font-weight: 600; font-size: 13px; }
  .inbox-card .m { color: var(--dim); font-size: 11px; text-transform: uppercase; letter-spacing: 0.12em; margin-bottom: 4px; }
  .inbox-card .b { color: var(--dim); font-size: 12px; margin-top: 4px; }
</style></head><body>
<header>
  <div class="logo"></div>
  <h1 id="title"></h1>
  <div class="meta" id="meta"></div>
</header>
<nav id="boards"></nav>
<main>
  <div class="canvas-wrap" id="canvas-wrap"></div>
  <aside><h2>All Cards</h2><div id="cards"></div></aside>
</main>
<script id="chitra-data" type="application/json">${json}</script>
<script>
(function () {
  const data = JSON.parse(document.getElementById('chitra-data').textContent);
  const proj = data.project;
  document.title = proj.name + ' · Chitra';
  document.getElementById('title').textContent = proj.name;
  document.getElementById('meta').textContent = proj.cards.length + ' cards · ' + proj.boards.length + ' boards · ' + new Date(data.generatedAt).toLocaleDateString();

  const cardById = new Map(proj.cards.map(c => [c.id, c]));
  const cardsEl = document.getElementById('cards');
  cardsEl.innerHTML = proj.cards.map(c =>
    '<div class="inbox-card"><div class="m">' + c.type + '</div><div class="t">' + escape(c.title) + '</div>' +
    (c.body ? '<div class="b">' + escape(c.body).slice(0, 200) + '</div>' : '') + '</div>'
  ).join('');

  const navEl = document.getElementById('boards');
  const wrap = document.getElementById('canvas-wrap');
  let activeId = proj.boards[0] && proj.boards[0].id;

  function renderBoard(boardId) {
    activeId = boardId;
    Array.from(navEl.children).forEach(c => c.classList.toggle('active', c.dataset.id === boardId));
    const b = proj.boards.find(x => x.id === boardId);
    if (!b) { wrap.innerHTML = ''; return; }
    const pad = 60;
    const w = (b.bbox.maxX - b.bbox.minX) + pad * 2;
    const h = (b.bbox.maxY - b.bbox.minY) + pad * 2;
    const ox = pad - b.bbox.minX, oy = pad - b.bbox.minY;
    const nodeById = new Map(b.nodes.map(n => [n.id, n]));
    const nodesSvg = b.nodes.map(n => {
      const card = cardById.get(n.cardId); if (!card) return '';
      const nw = n.width || 280, nh = n.height || 180;
      const x = n.position.x + ox, y = n.position.y + oy;
      const body = (card.body || '').slice(0, 100);
      return '<g transform="translate(' + x + ',' + y + ')">'
        + '<rect class="node" width="' + nw + '" height="' + nh + '"></rect>'
        + '<text class="node-type" x="14" y="22">' + escape(card.type) + '</text>'
        + '<text class="node-title" x="14" y="44">' + escape(card.title.slice(0, 32)) + '</text>'
        + (body ? '<foreignObject x="14" y="52" width="' + (nw - 28) + '" height="' + (nh - 60) + '"><div xmlns="http://www.w3.org/1999/xhtml" style="color:#9c9caa;font:11px Inter,sans-serif;line-height:1.4;">' + escape(body) + '</div></foreignObject>' : '')
        + '</g>';
    }).join('');
    const edgesSvg = b.edges.map(e => {
      const s = nodeById.get(e.source); const t = nodeById.get(e.target);
      if (!s || !t) return '';
      const sw = s.width || 280, sh = s.height || 180;
      const tw = t.width || 280, th = t.height || 180;
      const sx = s.position.x + ox + sw, sy = s.position.y + oy + sh / 2;
      const tx = t.position.x + ox, ty = t.position.y + oy + th / 2;
      const cx = (sx + tx) / 2;
      const path = 'M' + sx + ',' + sy + ' C' + cx + ',' + sy + ' ' + cx + ',' + ty + ' ' + tx + ',' + ty;
      return '<path class="edge" d="' + path + '"></path>'
        + (e.label ? '<text class="edge-label" x="' + cx + '" y="' + ((sy + ty) / 2 - 4) + '" text-anchor="middle">' + escape(e.label) + '</text>' : '');
    }).join('');
    wrap.innerHTML = '<svg width="' + w + '" height="' + h + '" xmlns="http://www.w3.org/2000/svg">'
      + '<defs><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto-start-reverse"><path d="M0,0 L10,5 L0,10 z" fill="rgba(255,255,255,0.35)"/></marker></defs>'
      + edgesSvg + nodesSvg + '</svg>';
  }

  proj.boards.forEach((b, i) => {
    const btn = document.createElement('button');
    btn.dataset.id = b.id; btn.textContent = b.name;
    if (i === 0) btn.classList.add('active');
    btn.addEventListener('click', () => renderBoard(b.id));
    navEl.appendChild(btn);
  });
  if (activeId) renderBoard(activeId);

  function escape(s) {
    return String(s == null ? '' : s).replace(/[&<>"']/g, m => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[m]));
  }
})();
</script>
</body></html>`;
}

/* ------------------------------------------------------------------ *
 *  Embeddable HTML (iframe snippet)                                   *
 * ------------------------------------------------------------------ */

/**
 * Wrap the interactive HTML in a base64 `srcdoc` iframe snippet that
 * can be pasted into Notion / Confluence / a static site. The iframe
 * is self-contained — no external assets, no network requests.
 */
export function projectToEmbedSnippet(
  project: Project,
  opts: { width?: string; height?: string; title?: string } = {},
): string {
  const html = projectToInteractiveHtml(project);
  const width = opts.width ?? "100%";
  const height = opts.height ?? "600";
  const title = (opts.title ?? `${project.name} \u2014 Chitra board`).replace(/"/g, "&quot;");
  // Use base64 instead of raw srcdoc to avoid quote/escape headaches when
  // pasted into HTML editors.
  const b64 = toBase64Utf8(html);
  return `<iframe\n  title="${title}"\n  src="data:text/html;base64,${b64}"\n  width="${width}"\n  height="${height}"\n  style="border:1px solid #2a2a35;border-radius:12px;background:#0a0a10;"\n  loading="lazy"\n  sandbox="allow-scripts allow-same-origin"\n></iframe>`;
}

function toBase64Utf8(s: string): string {
  // Browser + node 16+ both expose btoa, but btoa is latin-1 only. Round-trip
  // through UTF-8 bytes first.
  const bytes = new TextEncoder().encode(s);
  let binary = "";
  for (const b of bytes) binary += String.fromCharCode(b);
  // eslint-disable-next-line no-restricted-globals
  return typeof btoa === "function"
    ? btoa(binary)
    : Buffer.from(bytes).toString("base64");
}
