import type { Project } from "@chitra/core";
import { flattenBody, topoOrder } from "@chitra/exports";

/**
 * Build a Confluence "storage format" XHTML payload from a project.
 * Storage format ≈ a small subset of XHTML with `ac:` macros. We use only
 * plain headings, paragraphs, and bullet lists so it renders in any
 * Confluence Cloud instance without macro permissions.
 */
function escape(s: string): string {
  return s.replace(/[&<>"]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[m]!));
}

function buildStorageXhtml(project: Project, boardId?: string): string {
  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const boards = boardId ? project.boards.filter((b) => b.id === boardId) : project.boards;
  const out: string[] = [];
  out.push(`<p><em>Generated by Chitra on ${escape(new Date().toLocaleString())}</em></p>`);
  for (const b of boards) {
    out.push(`<h2>${escape(b.name)}</h2>`);
    if (b.nodes.length === 0) {
      out.push("<p><em>Empty board.</em></p>");
      continue;
    }
    const ordered = topoOrder(b.nodes, b.edges);
    for (const node of ordered) {
      const card = cardById.get(node.cardId);
      if (!card) continue;
      out.push(`<h3>${escape(card.title)} <em>· ${escape(card.type)}</em></h3>`);
      const body = flattenBody(card);
      if (body) out.push(`<p>${escape(body)}</p>`);
      const outs = b.edges.filter((e) => e.source === node.id);
      if (outs.length > 0) {
        out.push("<ul>");
        for (const e of outs) {
          const t = b.nodes.find((n) => n.id === e.target);
          const tc = t ? cardById.get(t.cardId) : undefined;
          if (!tc) continue;
          out.push(
            `<li><em>${escape(e.kind)}</em> → ${escape(tc.title)}${
              e.label ? ` (${escape(e.label)})` : ""
            }</li>`,
          );
        }
        out.push("</ul>");
      }
    }
  }
  return out.join("\n");
}

export type ConfluencePublishOptions = {
  baseUrl: string;
  email: string;
  /** API token from id.atlassian.com → Account Settings → Security. */
  token: string;
  spaceKey: string;
  project: Project;
  boardId?: string;
};

export async function publishToConfluence(
  opts: ConfluencePublishOptions,
): Promise<{ url: string }> {
  if (!opts.token) throw new Error("Confluence API token is not configured.");
  if (!opts.email) throw new Error("Confluence account email is not configured.");
  if (!opts.baseUrl) throw new Error("Confluence base URL is not configured.");
  if (!opts.spaceKey) throw new Error("Confluence space key is not configured.");

  const base = opts.baseUrl.replace(/\/+$/, "");
  const auth = Buffer.from(`${opts.email}:${opts.token}`).toString("base64");

  const body = {
    type: "page",
    title: `${opts.project.name} (Chitra · ${new Date().toISOString().slice(0, 10)})`,
    space: { key: opts.spaceKey },
    body: {
      storage: { value: buildStorageXhtml(opts.project, opts.boardId), representation: "storage" },
    },
  };

  const res = await fetch(`${base}/wiki/rest/api/content`, {
    method: "POST",
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
      Accept: "application/json",
    },
    body: JSON.stringify(body),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Confluence API ${res.status}: ${detail || res.statusText}`);
  }
  const json = (await res.json()) as { _links?: { base?: string; webui?: string } };
  const link = json._links?.base && json._links?.webui ? json._links.base + json._links.webui : "";
  return { url: link || `${base}/wiki/spaces/${opts.spaceKey}` };
}
