/**
 * Confluence publisher — runs in the browser.
 * Uses Basic auth with email + API token. Whether CORS allows it depends
 * on the Confluence Cloud instance configuration.
 */
import type { Project } from "@chitra/core";
import { flattenBody, topoOrder } from "@chitra/exports";

function escape(s: string): string {
  return s.replace(/[&<>"]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[m] ?? m));
}

function buildStorageXhtml(project: Project, boardId?: string): string {
  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const boards = boardId ? project.boards.filter((b) => b.id === boardId) : project.boards;
  const out: string[] = [];
  out.push(`<p><em>Generated by Chitra on ${escape(new Date().toLocaleString())}</em></p>`);
  for (const b of boards) {
    out.push(`<h2>${escape(b.name)}</h2>`);
    if (b.nodes.length === 0) {
      out.push("<p><em>Empty board.</em></p>");
      continue;
    }
    const ordered = topoOrder(b.nodes, b.edges);
    for (const node of ordered) {
      const card = cardById.get(node.cardId);
      if (!card) continue;
      out.push(`<h3>${escape(card.title)} <em>· ${escape(card.type)}</em></h3>`);
      const body = flattenBody(card);
      if (body) out.push(`<p>${escape(body)}</p>`);
      const outs = b.edges.filter((e) => e.source === node.id);
      if (outs.length > 0) {
        out.push("<ul>");
        for (const e of outs) {
          const t = b.nodes.find((n) => n.id === e.target);
          const tc = t ? cardById.get(t.cardId) : undefined;
          if (!tc) continue;
          out.push(
            `<li><em>${escape(e.kind)}</em> → ${escape(tc.title)}${
              e.label ? ` (${escape(e.label)})` : ""
            }</li>`,
          );
        }
        out.push("</ul>");
      }
    }
  }
  return out.join("\n");
}

export interface ConfluencePublishOptions {
  baseUrl: string;
  email: string;
  token: string;
  spaceKey: string;
  project: Project;
  boardId?: string;
}

function basicAuth(email: string, token: string): string {
  // Browser-safe base64. Use TextEncoder for UTF-8 safety.
  const bytes = new TextEncoder().encode(`${email}:${token}`);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}

export async function publishConfluence(
  opts: ConfluencePublishOptions,
): Promise<{ url: string }> {
  if (!opts.token) throw new Error("Confluence API token is not configured.");
  if (!opts.email) throw new Error("Confluence account email is not configured.");
  if (!opts.baseUrl) throw new Error("Confluence base URL is not configured.");
  if (!opts.spaceKey) throw new Error("Confluence space key is not configured.");

  const base = opts.baseUrl.replace(/\/+$/, "");
  const body = {
    type: "page",
    title: `${opts.project.name} (Chitra · ${new Date().toISOString().slice(0, 10)})`,
    space: { key: opts.spaceKey },
    body: {
      storage: { value: buildStorageXhtml(opts.project, opts.boardId), representation: "storage" },
    },
  };

  let res: Response;
  try {
    res = await fetch(`${base}/wiki/rest/api/content`, {
      method: "POST",
      headers: {
        Authorization: `Basic ${basicAuth(opts.email, opts.token)}`,
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new Error(
      "Confluence blocked the request (CORS or network). Use “Copy as XHTML” from the export menu, or configure CORS on your Confluence instance.",
    );
  }
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Confluence API ${res.status}: ${detail || res.statusText}`);
  }
  const json = (await res.json()) as { _links?: { base?: string; webui?: string } };
  const link = json._links?.base && json._links?.webui ? json._links.base + json._links.webui : "";
  return { url: link || `${base}/wiki/spaces/${opts.spaceKey}` };
}
