/**
 * Notion publisher — runs entirely in the browser.
 *
 * NOTE: Notion's API does NOT send CORS headers, so direct browser
 * requests fail in production browsers. Users who want one-click publish
 * need to set up a tiny CORS proxy (future feature) or use the
 * "Copy as Markdown" fallback exposed in the export menu.
 */
import type { Project } from "@chitra/core";
import { flattenBody, topoOrder } from "@chitra/exports";

const NOTION_VERSION = "2022-06-28";
const NOTION_API = "https://api.notion.com/v1";

type NotionBlock = Record<string, unknown>;

function rt(text: string): { type: "text"; text: { content: string } } {
  return { type: "text", text: { content: text.slice(0, 1990) } };
}

function p(text: string): NotionBlock {
  return { object: "block", type: "paragraph", paragraph: { rich_text: [rt(text)] } };
}
function h2(text: string): NotionBlock {
  return { object: "block", type: "heading_2", heading_2: { rich_text: [rt(text)] } };
}
function h3(text: string): NotionBlock {
  return { object: "block", type: "heading_3", heading_3: { rich_text: [rt(text)] } };
}
function bullet(text: string): NotionBlock {
  return {
    object: "block",
    type: "bulleted_list_item",
    bulleted_list_item: { rich_text: [rt(text)] },
  };
}
function divider(): NotionBlock {
  return { object: "block", type: "divider", divider: {} };
}

function buildBlocks(project: Project, boardId?: string): NotionBlock[] {
  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const boards = boardId ? project.boards.filter((b) => b.id === boardId) : project.boards;
  const blocks: NotionBlock[] = [];
  blocks.push(p(`Generated by Chitra · ${new Date().toLocaleString()}`));
  blocks.push(divider());
  for (const b of boards) {
    blocks.push(h2(b.name));
    if (b.nodes.length === 0) {
      blocks.push(p("Empty board."));
      continue;
    }
    const ordered = topoOrder(b.nodes, b.edges);
    for (const node of ordered) {
      const card = cardById.get(node.cardId);
      if (!card) continue;
      blocks.push(h3(`${card.title}  ·  ${card.type}`));
      const body = flattenBody(card);
      if (body) blocks.push(p(body));
      const outs = b.edges.filter((e) => e.source === node.id);
      for (const e of outs) {
        const t = b.nodes.find((n) => n.id === e.target);
        const tc = t ? cardById.get(t.cardId) : undefined;
        if (!tc) continue;
        blocks.push(bullet(`${e.kind} → ${tc.title}${e.label ? ` (${e.label})` : ""}`));
      }
    }
  }
  if (blocks.length > 99) {
    return [
      ...blocks.slice(0, 98),
      p("…(truncated — page contains additional content not shown)"),
    ];
  }
  return blocks;
}

export interface NotionPublishOptions {
  token: string;
  parentPageId: string;
  project: Project;
  boardId?: string;
}

export async function publishNotion(opts: NotionPublishOptions): Promise<{ url: string }> {
  if (!opts.token) throw new Error("Notion integration token is not configured.");
  if (!opts.parentPageId) throw new Error("Notion parent page id is not configured.");

  const body = {
    parent: { type: "page_id", page_id: opts.parentPageId.replace(/-/g, "") },
    properties: { title: { title: [rt(opts.project.name)] } },
    children: buildBlocks(opts.project, opts.boardId),
  };

  let res: Response;
  try {
    res = await fetch(`${NOTION_API}/pages`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${opts.token}`,
        "Notion-Version": NOTION_VERSION,
        "Content-Type": "application/json",
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    // Browser fetch + Notion = blocked by CORS. Surface clearly.
    throw new Error(
      "Notion blocked the request (CORS). Use “Copy as Markdown” from the export menu and paste into Notion, or run a CORS proxy.",
    );
  }
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`Notion API ${res.status}: ${detail || res.statusText}`);
  }
  const json = (await res.json()) as { url?: string };
  return { url: json.url ?? "" };
}
