import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from "docx";
import type { Project } from "@chitra/core";
import { flattenBody, topoOrder } from "@chitra/exports";

/**
 * Build a `.docx` `Document` from a project. Each board becomes a Heading 1
 * section; each card becomes a Heading 2 with body text + tag line.
 */
export function projectToDocx(project: Project): Document {
  const cardById = new Map(project.cards.map((c) => [c.id, c]));
  const children: Paragraph[] = [];

  children.push(
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.LEFT,
      children: [new TextRun({ text: project.name, bold: true })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated by Chitra · ${new Date().toLocaleString()}`,
          italics: true,
          color: "666666",
          size: 20,
        }),
      ],
    }),
    new Paragraph({ text: "" }),
  );

  for (const board of project.boards) {
    children.push(
      new Paragraph({
        heading: HeadingLevel.HEADING_1,
        children: [new TextRun({ text: board.name })],
      }),
    );
    if (board.nodes.length === 0) {
      children.push(new Paragraph({ children: [new TextRun({ text: "Empty board.", italics: true })] }));
      continue;
    }
    const ordered = topoOrder(board.nodes, board.edges);
    for (const node of ordered) {
      const card = cardById.get(node.cardId);
      if (!card) continue;
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          children: [new TextRun({ text: card.title })],
        }),
        new Paragraph({
          children: [
            new TextRun({ text: `Type: ${card.type}`, color: "888888", italics: true, size: 18 }),
          ],
        }),
      );
      const body = flattenBody(card);
      if (body) children.push(new Paragraph({ children: [new TextRun({ text: body })] }));
      if (card.tags.length > 0) {
        children.push(
          new Paragraph({
            children: [
              new TextRun({
                text: `Tags: ${card.tags.join(", ")}`,
                color: "888888",
                italics: true,
                size: 18,
              }),
            ],
          }),
        );
      }
      const outs = board.edges.filter((e) => e.source === node.id);
      if (outs.length > 0) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: "Connections:", bold: true, size: 20 })],
          }),
        );
        for (const e of outs) {
          const t = board.nodes.find((n) => n.id === e.target);
          const tc = t ? cardById.get(t.cardId) : undefined;
          if (!tc) continue;
          children.push(
            new Paragraph({
              bullet: { level: 0 },
              children: [
                new TextRun({ text: `${e.kind} → `, italics: true, color: "555555" }),
                new TextRun({ text: tc.title }),
                ...(e.label ? [new TextRun({ text: ` (${e.label})`, color: "888888" })] : []),
              ],
            }),
          );
        }
      }
      children.push(new Paragraph({ text: "" }));
    }
  }

  return new Document({
    creator: "Chitra",
    title: project.name,
    description: `Exported on ${new Date().toISOString()}`,
    sections: [{ children }],
  });
}

/** Returns the file as a Uint8Array using the browser-safe Packer.toBlob. */
export async function projectToDocxBytes(project: Project): Promise<Uint8Array> {
  const blob = await Packer.toBlob(projectToDocx(project));
  return new Uint8Array(await blob.arrayBuffer());
}
